### PR TITLE
feat: add rendering for experience projects

### PR DESCRIPTION
**Pull request by abubics**
- release 0.0.12

### CODE REVIEW

**Review by srbartlett — APPROVED** [review]
LGTM Boris 👍

**Review by warnergodfrey — APPROVED** [review]
I tested this locally and it looks good. @abubics are you able to generate and deploy the package?

**Comment by abubics** [comment]
I can at least attempt to follow the instructions ;) last time I tried, I couldn't get to the stage of testing the bundle in precise.io.

**Comment by srbartlett** [comment]
Yell out if you get stuck @abubics. Give this Loom a go if the instructions don't make sense.  First thing, check you are an account Admin in Precise.  https://www.loom.com/share/9e19837b79464a22a93078b6559a6557

**Comment by tarciosaraiva** [comment]
Good collaboration guys, keep it going 👍

**Pull request merged**
